// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $MyCounter from "./islands/MyCounter.tsx";
import * as $Resume_ExperienceItem from "./islands/Resume/ExperienceItem.tsx";
import * as $Resume_Header from "./islands/Resume/Header.tsx";
import * as $Resume_Resume from "./islands/Resume/Resume.tsx";
import * as $Resume_SectionCertifications from "./islands/Resume/SectionCertifications.tsx";
import * as $Resume_SectionEducation from "./islands/Resume/SectionEducation.tsx";
import * as $Resume_SectionExperience from "./islands/Resume/SectionExperience.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/MyCounter.tsx": $MyCounter,
    "./islands/Resume/ExperienceItem.tsx": $Resume_ExperienceItem,
    "./islands/Resume/Header.tsx": $Resume_Header,
    "./islands/Resume/Resume.tsx": $Resume_Resume,
    "./islands/Resume/SectionCertifications.tsx": $Resume_SectionCertifications,
    "./islands/Resume/SectionEducation.tsx": $Resume_SectionEducation,
    "./islands/Resume/SectionExperience.tsx": $Resume_SectionExperience,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
